AllCops:
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 128

Style/Documentation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

Style/ModuleFunction:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassVars:
  Enabled: false
